server.port=8083
spring.application.name=anonymization-service
anonymization.default-method=hash
logging.level.root = debug
auth.service.url=http://localhost:8085/auth/validate
slow.controller.delay=2000
flaky.controller.rate=0.5

