server.port=8083
spring.application.name=anonymization-service
anonymization.default-method=hash
logging.level.root = debug
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

auth.service.url=${AUTH_URL:http://localhost:8085/auth/validate}
slow.controller.delay=2000
flaky.controller.rate=0.5
server.tomcat.max-swallow-size=20MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

