# Build stage
FROM maven:3.8.6-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Run stage
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/anonymization-service-*.jar /app/anonymization-service.jar
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "anonymization-service.jar"]