server.port=8080
spring.application.name=coordinator-service
#logging.level.root = debug
logging.level.org.springframework.web=DEBUG
service.nonexistent.url=http://nonexistent:8080


# Service URLs production
#service.filter.url=http://filter-service:8081
#service.aggregation.url=http://aggregation-service:8082
#service.anonymization.url=http://anonymization-service:8083
#service.formatting.url=http://formatting-service:8084

# Service URLs DEV
service.filter.url=http://localhost:8081
service.aggregation.url=http://localhost:8082
service.anonymization.url=http://localhost:8083
service.formatting.url=http://localhost:8084

# Pipeline directory (can be overridden with command line arg)
pipeline.input-dir=classpath:pipelines

# Circuit Breaker
#resilience4j.circuitbreaker.instances.filter-service.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.filter-service.wait-duration-in-open-state=5000
#resilience4j.circuitbreaker.instances.filter-service.permitted-number-of-calls-in-half-open-state=3
#resilience4j.circuitbreaker.instances.filter-service.sliding-window-size=10