spring.application.name=filter-service
server.port=8081
logging.level.root = debug
auth.service.url=http://localhost:8085/auth/validate
service.anonymization.url=http://localhost:8083
slow.controller.delay=2000
flaky.controller.rate=0.5
