spring.application.name=filter-service
server.port=8081
logging.level.root = debug
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
auth.service.url=http://localhost:8085/auth/validate
service.anonymization.url=http://localhost:8083
slow.controller.delay=2000
flaky.controller.rate=0.5
server.tomcat.max-swallow-size=20MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
