spring.application.name=data-product-service
server.port=8089
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB
server.max-http-request-header-size=16384
server.tomcat.max-http-form-post-size=10485760


logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.org.springframework.feign.codec= DEBUG
